[etcd]
namespace = "local"                         # env: BACKEND_NAMESPACE
addr = { host = "127.0.0.1", port = 2379 }  # env: BACKEND_ETCD_ADDR (host:port)
user = ""                                   # env: BACKEND_ETCD_USER
password = ""				    # env: BACKEND_ETCD_PASSWORD


[agent]
# Agent mode; required
mode = "scratch"

# Change the reported host/address of the agent.
# The manager will use this value to connect to the agent.
# If host is an empty string, the agent tries to auto-detect it with a fallback to "127.0.0.1".
# For mobile environments such as developer laptops which roam around different networks,
# it is HIGHLY RECOMMENDED to set this to "127.0.0.1" manually.
rpc-listen-addr = { host = "127.0.0.1", port = 8130 }
# UID and GID of user which will run Backend.AI agent.
user-uid = 1000
user-gid = 1000

[storage]
# Storage mode; currently we support XFS only.
mode = "xfs"
# Root path where XFS partitions is mounted.
path = "/xfs"
