[etcd]
namespace = "local"
addr = { host = "127.0.0.1", port = 8120 }
user = ""
password = ""

[agent]
mode = "scratch"
rpc-listen-addr = { host = "127.0.0.1", port = 8130 }

[storage]
mode = "xfs"
path = "/xfs"
