[etcd]
namespace = "local"                         # env: BACKEND_NAMESPACE
addr = { host = "127.0.0.1", port = 2379 }  # env: BACKEND_ETCD_ADDR (host:port)
user = ""                                   # env: BACKEND_ETCD_USER
password = ""				    # env: BACKEND_ETCD_PASSWORD


[agent]
# The service address
proxy-addr = { host = "0.0.0.0", port = 6021 }
rpc-listen-addr = { host = "127.0.0.1", port = 6020 }


[logging]
# One of: "NOTSET", "DEBUG", "INFO", "WARNING", "ERROR", "CRITICAL"
# Set the global logging level.
level = "INFO"

# Multi-choice of: "console", "logstash", "file"
# For each choice, there must be a "logging.<driver>" section
# in this config file as exemplified below.
drivers = ["console"]


[logging.console]
# If set true, use ANSI colors if the console is a terminal.
# If set false, always disable the colored output in console logs.
colored = true

# One of: "simple", "verbose"
format = "simple"


[storage]
# storage section may define one or more named subsections with
# backend-specific configurations.


[storage.local]
# The default, generic filesystem.
# It uses the standard syscalls to perform filesystem operations
# such as scanning the file/directory metadata.
# This does *NOT* support per-direcotry quota.
backend = "vfs"
path = "/vfroot/xfs"


[storage.fastlocal]
# An extended version for XFS, which supports per-directory quota
# based on xfs projects.
backend = "xfs"
path = "/vfroot/xfs"


[storage.mypure]
# An extended version for PureStorage FlashBlade nodes, which uses
# RapidFile Tools to perform filesystem metadata queries and the
# FB REST APIs to configure per-directory quota.
backend = "purestorage"
path = "/vfroot/fb1"
purity_endpoint = "192.168.0.10:443"
purity_ssl_verify = false
purity_api_token = "xxxxxx"
purity_fs_name = "mypure"  # the name of filesystem used by the filesystem API


[storage.myceph]
# An extended version for CephFS, which supports extended inode attributes
# for per-directory quota and fast metadata queries.
backend = "cephfs"
path = "/vfroot/ceph-fuse"
